### ISSUE TITLE
How to get the onclickListener for close and finish indicators?

### ISSUE THREAD

**Issue by Crusher7** [meNESS/EasyIntro#12]

**Comment by meNESS** [comment]
@Crusher7 Take a look at [callbacks wiki page](https://github.com/meNESS/EasyIntro/wiki/Callbacks) please. If that didn't help, let me know.

**Comment by Crusher7** [comment]
I did that, but something is going wrong!, it's showing me errors while writing these methods ..
did i make mistakes or something should I do before calling these methods? 

```
 @Override   // Error here is:  Method dose not override method from its superclass
    public void onSlideChanged(Fragment fragment) {
        super.onSlideChanged(fragment);
        // ...
    }

**Comment by Crusher7** [comment]
Okay ... Thank you for help, I removed what was in the brackets and now it's working .. 
```
@Override
    public void onDonePressed() {
        super.onDonePressed();
        Intent intent = new Intent(this,MainActivity.class);
        startActivity(intent);
    }
```
Is it the right way to do it?

**Comment by meNESS** [comment]
@Crusher7 Yes, you doing it right 👍
