### ISSUE TITLE
I got an error 

### ISSUE THREAD

**Issue by kikirizki** [meNESS/EasyIntro#5]
Error:(28, 13) Failed to resolve: io.github.meness:easyintro:1.2.6
<a href="openFile:/root/AndroidStudioProjects/nextintro/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by meNESS** [comment]
@kikirizki I think you're trying to include the library in your project and there's something wrong with your `build.gradle`. Please give me your `build.gradle` files (both project and module).

**Comment by kikirizki** [comment]
this is my build.gradle (module):
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    repositories{
        maven {
            url "https://jitpack.io"
        }
    }
    defaultConfig {
        applicationId "com.example.root.pembayaran"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.github.meNESS:EasyIntro:1.2.6'
}
`
this is my build.gradle (project):

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()


    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by meNESS** [comment]
@kikirizki Dependencies are case-sensitive. Use `compile 'io.github.meness:easyintro:1.2.6` instead.

**Comment by meNESS** [comment]
@kikirizki Did it help?

**Comment by CarlosJJR** [comment]
I'm having the exact same problem. Any idea what the problem is?? Here's my gradle file

    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.2"

        defaultConfig {
            applicationId "mobile.mx.nycmesoamerica"
            minSdkVersion 17
            targetSdkVersion 23
            versionCode 1
            versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
        dataBinding {
            enabled = true
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'

        compile 'com.android.support:appcompat-v7:23.3.0'
        compile 'com.android.support:design:23.3.0'
        compile 'com.android.support:support-v4:23.3.0'
        compile 'com.google.android.gms:play-services-maps:8.4.0'
        compile 'com.facebook.android:facebook-android-sdk:4.10.1'
        compile 'com.parse.bolts:bolts-tasks:1.3.0'
        compile 'com.parse:parse-android:1.13.0'
        compile 'de.hdodenhof:circleimageview:2.0.0'
        compile 'com.thefinestartist:ytpa:1.2.1'
        compile 'com.squareup.picasso:picasso:2.5.2'
        compile 'io.github.meness:easyintro:1.2.9'
    }

**Comment by meNESS** [comment]
@CarlosJJR @kikirizki Both of you probably enabled the 'offline work' option in settings. Consider disabling that option and try building again. there's no problem with the EasyIntro and/or your usage. You must try to build your project and download the modified version of libraries. If no cached version of libraries found, you'll get 'Failed to resolve' error while building. If you have access to bintray website without proxy, you can build easily but if your access is limited, you must configure Gradle to use a proxy.

**Comment by CarlosJJR** [comment]
I am not using offline work. I double checked and I am able to add any other library through gradle without a problem. Any idea what else could it be?
<img width="788" alt="screen shot 2016-05-07 at 11 05 24" src="https://cloud.githubusercontent.com/assets/6587434/15093139/d776b5d0-1443-11e6-80ee-83cc8789c598.png">

**Comment by meNESS** [comment]
@CarlosJJR Please put the module `build.gradle` file here. I think other solution is check to have both `jcenter()` and `mavenCentral()`.

**Comment by CarlosJJR** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:2.1.0'

            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }

    allprojects {
        repositories {
            jcenter()
            mavenCentral()
        }
    }

    task clean(type: Delete) {
        delete rootProject.buildDir
    }

**Comment by meNESS** [comment]
@CarlosJJR Do you have easy access to this [link](https://bintray.com/meness/maven/easyintro/view)? Please test without any VPN/Proxy. Everything looks fine. If you have easy access to that link, so there should not be any problem, Otherwise, you must update Gradle with configured proxy.

**Comment by CarlosJJR** [comment]
@meNESS I had no problem opening the link you provided. I'm really curious now on what the problem could be. Everything seems to be in place but I still can't get the library. I ended up cloning the repo and adding the dependence from the project folder.

**Comment by meNESS** [comment]
@CarlosJJR Another solution could be using jitpack but believe me there's no problem with the library because I'm using it in my projects without any problem! Please replace `mavenCentral()` with `mavenLocal()` and build again, then tell me the result. Thanks.

**Comment by CarlosJJR** [comment]
@meNESS I tried your suggestion but still nothing. Thanks anyway

**Comment by meNESS** [comment]
@kikirizki @CarlosJJR Sorry guys. I didn't know that the library actually doesn't exists on jCenter! I requested just now and it may takes 1 day to be approved.

**Comment by CarlosJJR** [comment]
Thanks @meNESS
